In [1]:
import numpy as np

In [2]:
a7=np.arange(4).reshape(4,1)
a8=np.arange(12).reshape(4,3)
print(a7)
print(a8)

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [3]:
a7+a8

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [5]:
np.random.random()

0.9917719188397927

In [11]:
np.random.seed(100)
np.random.random()

0.5434049417909654

In [17]:
np.random.uniform(3,100)

68.06266121849752

In [19]:
np.random.uniform(1,100,10).reshape(2,5)

array([[18.02216026, 81.80625012, 28.13330096, 43.73871418, 94.06295214],
       [81.9472885 , 34.27508306, 18.36563492, 37.91037258,  1.56316223]])

In [22]:
np.random.randint(1,10,15).reshape(3,5)

array([[8, 7, 3, 1, 9],
       [3, 6, 2, 9, 2],
       [6, 5, 3, 9, 4]])

In [23]:
a=np.random.randint(1,10,6)

In [24]:
a

array([6, 1, 4, 7, 4, 5])

In [25]:
np.max(a)

7

In [26]:
np.min(a)

1

In [27]:
np.argmax(a)

3

In [28]:
a[np.argmin(a)]

1

In [30]:
a=np.random.randint(1,10,6)
a

array([6, 8, 7, 7, 3, 5])

In [31]:
a[a%2==1]=-1
a

array([ 6,  8, -1, -1, -1, -1])

In [43]:
a=np.random.randint(1,50,6)
a

array([36, 24, 10, 49, 49, 22])

In [34]:
np.where(a%2==1,1,a)


array([ 1,  1,  1, 20,  1,  1])

In [44]:
a

array([36, 24, 10, 49, 49, 22])

In [45]:
a=np.sort(a)
a

array([10, 22, 24, 36, 49, 49])

In [36]:
np.percentile(a,25)

5.0

In [37]:
np.percentile(a,50)

12.5

In [47]:
np.percentile(a,100)

49.0